### ISSUE TITLE
Add IRC server password

### ISSUE THREAD

**Issue by ThisIsTheOnlyUsernameAvailable** [weannounce/arrnounced#25]
Great project.  Thanks for your work on it.

I'd like to connect to an IRC server that requires a password.  I've looked through the source and can't find any options built into the code.

Is this something that's easy to include from the underlying libraries?

**Comment by weannounce** [comment]
Hey, thanks!

You are correct, there is no support for that atm. I haven't got any prior experience with this, is it [SASL authentication](https://ircv3.net/specs/extensions/sasl-3.1.html) you're looking for? Arrnounced uses `pydle` for IRC support, and `pydle` supports SASL, so it shouldn't be much problem to add it.

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
Hi,

Thanks for the response.  I'm hoping to use the basic server password functionality.  I had a look at Pydle, and it looks like it's poorly documented, but is there.

[Here](https://github.com/Shizmob/pydle/issues/72) is a support ticket that describes how to do it.  Unfortunately I am not very adept at coding so am unsure if this is a significant request.  The use of ZNC isn't unusual in this space, so I do think it'd be an appreciated feature to a broader audience.

**Comment by weannounce** [comment]
I did the changes, but had trouble getting my IRC test server to accept a password. Haven't found the time to make sure it works yet. The changes are easy enough that I cannot see how they wouldn't work. Until I have time to test it, I published a prerelease that you can use. https://pypi.org/project/arrnounced/0.9.1a0/ 

Does that work for you?

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
Thanks very much!  I'll test in the next day or so.

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
Just to let you know that I still plan to get this tested.  I'm currently running into a problem with the latest version of Jinja2 removing the `escape` function which is causing the build to fail.  I'll come back to you shortly.

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
Ok, I worked out the dependency issues.  That was painful!

The IRC password grants access to the server.  Thank you.  A couple of observations that may be owing to using a debug version.  The first is that it fails if I don't set the `irc_password` in the config.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/arrnounced/irc.py", line 203, in run
    password=tracker.config.irc_password,
  File "/usr/local/lib/python3.9/site-packages/arrnounced/tracker.py", line 210, in irc_password
    return str(self._user_tracker["irc_password"])
KeyError: 'irc_password'
2022-04-06 18:13:47,826 - WARNING:werkzeug                     - WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
 * Serving Flask app "Arrnounced" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.

```

The other is that each release has a warning message associated, even though it is correctly connected to Sonarr/Radarr:

```
 WARNING:BACKEND                      - No valid JSON reply from Radarr
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/arrnounced/backend.py", line 14, in _extract_approval
    return json_response["approved"]
```
